AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/BlockLength:
  Exclude: ['spec/*', 'config.ru']

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude: ['spec/*']
