AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/BlockLength:
  Exclude: ['spec/*']

Layout/LineLength:
  Max: 86
  Exclude: ['spec/*']
